---
title: "Publications"
output: html_document
---

### *Under review*

**James WR**, Furman BT, Rodemann JR, Costa SV, Fratto ZW, Nelson JA, Rehage JS, & RO Santos (*in review*) Widespread habitat loss leads to ecosystem-scale decrease in trophic function.

Santos RO, **James WR**, Rehage JS, Eggenberger CW, Lesser JS, & CJ Madden (*in review*) Trophic niche dynamics of two fish mesoconsumers in adjacent coastal habitats with varying nutrient regimes.

Linenfelser JO, **James WR**, Rezek RJ, Santos RO, Frankovich TA, Madden C, Nelson JA, & JS Rehage (*in review*) Tracing the source of nutrients entering North-Central Florida Bay: a stable isotope approach.

Castillo NA, **James WR**, Santos RO, Cerveny D, Boucek RE, Adams AJ, Goldberg T, Campbell L, Perez AU, Schmitter-Soto JJ, Lewis JP, Fick J, Brodin T, & JS Rehage (*in review*) Understanding pharmaceutical exposure and the potential for effects in marine biota: a survey of bonefish (Albula vulpes) across the Caribbean Basin.

Massie JA, Rezek RJ, **James WR**, Santos RO, Viadero NM, Boucek RE, & JS Rehage (*in review*) When the timing is right: linking a seasonal freshwater prey subsidy to the body condition of an estuarine consumer in a subtropical coastal river.

Jones BLH, Santos RO, **James WR**, Costa SV, Adams AJ, Boucek RE, Coals LRM, Cullen-Unsworth LC, Shephard S, & JS Rehage (*in review*) Lack of evolution in fisheries-associated Indigenous and local knowledge research reveals opportunities for growth.

Castillo NA, Santos RO, **James WR**, Rezek RJ, Cervany D, Boucek RE, Fick J, Brodin T, & JS Rehage (*in review*) Widespread pharmaceutical exposure at concentrations of concern for a subtropical coastal fishery: Bonefish (Albula vulpes). [Pre-print](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=4394268)

Rehage JS, Castillo NA, Distrubell A, Trabelsi S, Santos RO, **James WR**, Rezek R, Cerveny D, Boucek RE, Adams AJ, Fick J, & T Brodin (*in review*) A multi-estuary assessment of pharmaceutical exposure and risk of pharmacological effects in a recreational fishery.

Raoult V, Phillips AA, Nelson JA, Niella Y, Skinner C, Tilcock MB, Burke PJ, Szpak P, **James WR**, & C Harrod (*in review*) Beyond carbon and nitrogen: the case for adding sulfur ($\delta^{34}$S) to the stable isotope toolkit.

### *Peer Reviewed*

#### **2023**

Gervasi CL, Karnauskas M, Rios A, Santos RO, **James WR**, Rezek RJ, & JS Rehage (2023) Rapid approach for assessing an unregulated fishery using a series of data-limited tools.<https://doi.org/10.1002/mcf2.10270>\

Yando ES†, Jones SF†, **James WR†**, Colombano DD, Montemayor DI, Nolte S, Raw JL, Ziegler SL, Chen L, Daffonchio D, Fusi M, Rogers K, & L Sergienko. (2023) An integrative salt marsh conceptual framework for global comparisons. *Limnology and Oceanography Letters* <https://doi.org/10.1002/lol2.10346>\
*†Contributed equally*\

Iporac LAR, **James WR**, & Collado-Vides L (2023) Characterizing potential resource use of sargasso-dominant sea wrack by terrestrial invertebrate fauna during sargasso influxes in South Florida. *Estuarine, Coastal and Shelf Science* <https://doi.org/10.1016/j.ecss.2023.108414>\

Rezek RJ, Massie JA, Nelson JA, Santos RO, Viadero NM, **James WR**, Boucek RE, & JS Rehage (2023) The effects of temperature and flooding duration on the structure and magnitude of a floodplain prey subsidy. *Freshwater Biology* <https://doi.org/10.1111/fwb.14145>\

Rodemann JR, **James WR**, Rehage JS, Baktoft H, Costa SV, Ellis RD, Gonzalez L & RO Santos (2023) Residency and fine-scale habitat use of juvenile goliath grouper (*Epinephelus itajara*) in a mangrove nursery. *Bulletin of Marine Science* <https://doi.org/10.5343/bms.2022.0061>\

Calhoun-Grosch S, Foster EM, **James WR**, Santos RO, Rehage JS, & JA Nelson (2023) Trophic niche metrics reveal long-term shift in Florida Bay food webs. *Ecosystems* <https://doi.org/10.1007/s10021-023-00825-5>\

#### **2022**

Massie JA, Santos, RO, Rezek, RJ, **James, WR**, Viadero, NM, Boucek, RE, Blewett DA, Trotter AA, Stevens PW, & JS Rehage (2022) Primed and cued: long-term acoustic telemetry links interannual and seasonal variations in freshwater flows to the spawning migrations of Common Snook in the Florida Everglades. *Movement Ecology* <https://doi.org/10.1186/s40462-022-00350-5>\

Gervasi CL, Nelson JA, Swart PK, Santos RO, Rezek RJ, **James WR**, Jefferson AE, Drymon JM, Carroll J, Boucek RE, & JS Rehage (2022) Otolith stable isotope micro-sampling to discriminate poorly studied stocks: Crevalle Jack in the eastern Gulf of Mexico. *Estuarine, Coastal and Shelf Science* <https://doi.org/10.1016/j.ecss.2022.108130>\

**James WR**, Bautista V, Rezek RJ, Zink IC, Rehage JS, & RO Santos (2022) A review of the potential impacts of commercial inshore pink shrimp fisheries on recreational flats fisheries in Biscayne Bay, FL, USA. *Environmental Biology of Fishes* <https://doi.org/10.1007/s10641-022-01319-4>\
[*-Special issue: Conservation Connections: Science informing management for flats fisheries*](https://link.springer.com/collections/bccedjgibi)

Rezek RJ, **James WR**, Bautista V, Zink IC, Rehage JS, & RO Santos (2022) Temporal trends of Biscayne Bay pink shrimp fisheries catch and economic indicators. *Environmental Biology of Fishes* <https://doi.org/10.1007/s10641-022-01314-9>\
[*-Special issue: Conservation Connections: Science informing management for flats fisheries*](https://link.springer.com/collections/bccedjgibi)

**James WR**, Santos RO, Rodemann JR, Rezek RJ, Fratto ZW, Furman BT, Hall MO, Kelble CR, Rehage JS, & JA Nelson (2022) Widespread seagrass die-off has no legacy effect on basal resource use of seagrass food webs in Florida Bay, USA. *ICES Journal of Marine Science* fsac112, <https://doi.org/10.1093/icesjms/fsac112>

Santos RO, **James WR**, Nelson JA, Rehage JS, Serafy J, Pittman SJ, & D Lirman (2022) Influence of seascape spatial pattern on the trophic niche of an omnivorous fish. *Ecosphere* <https://doi.org/10.1002/ecs2.3944>

#### **2021**

**James WR**, Santos RO, Rehage JS, Doerr JC, & JA Nelson (2021) *E*-scape: consumer specific landscapes of energetic resources derived from stable isotope analysis and remote sensing. *Journal of Animal Ecology* <https://doi.org/10.1111/1365-2656.13637> [*Pre-print*](https://doi.org/10.1101/2020.08.03.234781)

Rodemann JR, **James WR**, Santos RO, Furman BT, Fratto ZW, Bautista V, Hernandez JL, Viadero NM, Linenfelser JO, Lacy LA, Hall MO, Kelble CR, Kavanaugh C, & JS Rehage (2021) Impact of extreme disturbances on suspended sediment in Western Florida Bay: Implications for seagrass resilience. *Frontiers in Marine Science* <https://doi.org/10.3389/fmars.2021.633240>\
[*-Special issue: Environmental Threats to the State of Florida---Climate Change and Beyond*](https://www.frontiersin.org/research-topics/14439/environmental-threats-to-the-state-of-florida-climate-change-and-beyond#articles)

Gervasi CL, Santos RO, Rezek RJ, **James WR**, Boucek RE, Bradshaw C, Kavanagh C, Osborne J, & JS Rehage (2021) Bottom-up conservation: Using translational ecology to inform conservation priorities for a recreational fishery. *Canadian Journal of Fisheries and Aquatic Sciences* <https://doi.org/10.1139/cjfas-2021-0024>\

Kimball ME, Connolly RM, Alford SB, Colombano DD, **James WR**, Kenworth MD, Norris GS, Ollerhead J, Ramsden S, Rehage JS, Sparks EL, Waltham NJ, Worthington TA, & MD Taylor (2021) Novel applications of technology for advancing tidal marsh ecology. *Estuaries & Coasts* [doi: 10.1007/s12237-021-00939-w](https://link.springer.com/article/10.1007/s12237-021-00939-w)\
[*-Special issue: Concepts and controversies in tidal marsh ecology revisited*](https://link.springer.com/journal/12237/volumes-and-issues/44-6)

Pittman SJ, Yates KL, Bouchet PJ,... **James WR**... (34 additional authors) (2021) Seascape ecology: Identifying research priorities for an emerging ocean sustainability science. *Marine Ecology Progress Series* <https://doi.org/10.3354/meps13661>\

#### **2020**

Nelson JA, Harris JM, Lesser JS, **James WR**, Suir SM, & WP Broussard III (2020) New mapping metrics to test functional response of food webs to coastal restoration. *Food webs* <https://doi.org/10.1016/j.fooweb.2020.e00179>\
[*-Special issue: Restoration Initiatives Viewed Through a Lens of Food Web Structure and Dynamics*](https://www.sciencedirect.com/journal/food-webs/special-issue/10BB11JLN9G)

Jones SF, Stagg CL, Yando ES, **James WR**, Buffington KJ, & MW Hester (2020) Stress gradients interact with disturbance to reveal alternative states in salt marsh: Multivariate resilience at the landscape scale. *Journal of Ecology* <https://doi.org/10.1111/1365-2745.13552>\
[*-Special issue: Reconciling resilience across ecological systems, species and subdisciplines*](https://besjournals.onlinelibrary.wiley.com/hub/ecological_resilience)

Baker R, Taylor MD, Beck MW, Cebrian J, Colombano DD, Connolly RM, Currin C, Deegan LA, Feller IC, Gilby BL, Kimball ME, Minello TJ, Rozas LP, Simenstad C, Turner RE, Waltham NJ, Weinstein MP, Ziegler SL, zu Ermgassen PSE, ... **James WR**... (29 additional authors) (2020) Fisheries rely on threatened salt marshes. *Science* [DOI: 10.1126/science.abe9332](https://science.sciencemag.org/content/370/6517/670.1.full)

**James WR**, Topor ZM, & RO Santos (2020) Seascape structure influences the community structure of marsh nekton. *Estuaries & Coasts* [doi: 10.1007/s12237-020-00853-7](https://link.springer.com/article/10.1007/s12237-020-00853-7)\
[*-Special issue: Concepts and controversies in tidal marsh ecology revisited*](https://link.springer.com/journal/12237/volumes-and-issues/44-6)

Harris JM†, **James WR†**, Lesser JS†, Doerr JC, & JA Nelson (2020) Foundation species shift alters the energetic landscape of marsh nekton. Estuaries & Coasts [doi: 10.1007/s12237-020-00852-8](https://link.springer.com/article/10.1007/s12237-020-00852-8)\
*†Contributed equally*\
[*-Special issue: Concepts and controversies in tidal marsh ecology revisited*](https://link.springer.com/journal/12237/volumes-and-issues/44-6)

Lesser JS, **James WR**, Stallings CD, Wilson RM, & JA Nelson (2020) Trophic niche size and overlap decrease with increasing ecosystem productivity. *Oikos* <https://doi.org/10.1111/oik.07026>

#### **2019**

**James WR**, JS Lesser, SY Litvin, & JA Nelson (2019) Assessment of food web recovery following restoration using resource use metrics. *Science of the Total Environment* <https://doi.org/10.1016/j.scitotenv.2019.134801>

Nelson JA, Lesser JS, **James WR**, Behringer DP, Furka V, & JC Doerr (2019) Food web response to foundation species change in a coastal ecosystem. *Food Webs* <https://doi.org/10.1016/j.fooweb.2019.e00125>

Eggenberger CW, Santos RO, Frankovich T, **James WR**, Madden C, Nelson JA, & JS Rehage (2019) Coupling telemetry and stable isotope techniques to unravel movement: Snook habitat use across variable nutrient environments. *Fisheries Research* <https://doi.org/10.1016/j.fishres.2019.04.008>

#### **2018 and earlier**

**James WR**, Styga JM, White S, Marson KM, & RL Earley (2018) Developmentally plastic responses to predation threat in the mangrove rivulus fish (*Kryptolebias marmoratus*): behavior and morphology. *Evolutionary Ecology* <https://doi.org/10.1007/s10682-018-9952-5>

**James WR** & JB McClintock (2017) Anti-predator responses of amphipods are more effective in the presence of conspecific chemical cues. *Hydrobiologia* <https://doi.org/10.1007/s10750-017-3191-6>

Smith KE, Aronson RB, Steffel BV, Amsler MO, Thatje S, Singh H, Anderson J, Brother CJ, Brown A, Ellis DS, Havenhand JN, **James WR**, Mosknes P, Randolph AW, Sayre-McCord T, & JB McClintock (2017) Climate change and the threat of novel marine predators in Antarctica. *Ecosphere* <https://doi.org/10.1002/ecs2.2017>
